//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace whusap.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ent_tticol125", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Ent_tticol125 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pdnoField;
        
        private int ponoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string itemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cwarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string clotField;
        
        private int reqtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateField;
        
        private int prinField;
        
        private int confField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string refcntdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string refcntuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idrecordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string pdno {
            get {
                return this.pdnoField;
            }
            set {
                if ((object.ReferenceEquals(this.pdnoField, value) != true)) {
                    this.pdnoField = value;
                    this.RaisePropertyChanged("pdno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int pono {
            get {
                return this.ponoField;
            }
            set {
                if ((this.ponoField.Equals(value) != true)) {
                    this.ponoField = value;
                    this.RaisePropertyChanged("pono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string item {
            get {
                return this.itemField;
            }
            set {
                if ((object.ReferenceEquals(this.itemField, value) != true)) {
                    this.itemField = value;
                    this.RaisePropertyChanged("item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cwar {
            get {
                return this.cwarField;
            }
            set {
                if ((object.ReferenceEquals(this.cwarField, value) != true)) {
                    this.cwarField = value;
                    this.RaisePropertyChanged("cwar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string clot {
            get {
                return this.clotField;
            }
            set {
                if ((object.ReferenceEquals(this.clotField, value) != true)) {
                    this.clotField = value;
                    this.RaisePropertyChanged("clot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int reqt {
            get {
                return this.reqtField;
            }
            set {
                if ((this.reqtField.Equals(value) != true)) {
                    this.reqtField = value;
                    this.RaisePropertyChanged("reqt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                if ((object.ReferenceEquals(this.dateField, value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int prin {
            get {
                return this.prinField;
            }
            set {
                if ((this.prinField.Equals(value) != true)) {
                    this.prinField = value;
                    this.RaisePropertyChanged("prin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int conf {
            get {
                return this.confField;
            }
            set {
                if ((this.confField.Equals(value) != true)) {
                    this.confField = value;
                    this.RaisePropertyChanged("conf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string refcntd {
            get {
                return this.refcntdField;
            }
            set {
                if ((object.ReferenceEquals(this.refcntdField, value) != true)) {
                    this.refcntdField = value;
                    this.RaisePropertyChanged("refcntd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string refcntu {
            get {
                return this.refcntuField;
            }
            set {
                if ((object.ReferenceEquals(this.refcntuField, value) != true)) {
                    this.refcntuField = value;
                    this.RaisePropertyChanged("refcntu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string mess {
            get {
                return this.messField;
            }
            set {
                if ((object.ReferenceEquals(this.messField, value) != true)) {
                    this.messField = value;
                    this.RaisePropertyChanged("mess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string idrecord {
            get {
                return this.idrecordField;
            }
            set {
                if ((object.ReferenceEquals(this.idrecordField, value) != true)) {
                    this.idrecordField = value;
                    this.RaisePropertyChanged("idrecord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.InterfazServicioWhusa")]
    public interface InterfazServicioWhusa {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfazServicioWhusa/enviaDatos", ReplyAction="http://tempuri.org/InterfazServicioWhusa/enviaDatosResponse")]
        whusap.ServiceReference1.enviaDatosResponse enviaDatos(whusap.ServiceReference1.enviaDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfazServicioWhusa/CambiaEstado", ReplyAction="http://tempuri.org/InterfazServicioWhusa/CambiaEstadoResponse")]
        whusa.Entidades.Ent_tticol125[] CambiaEstado(whusa.Entidades.Ent_tticol125 parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfazServicioWhusa/recuperarCliente", ReplyAction="http://tempuri.org/InterfazServicioWhusa/recuperarClienteResponse")]
        whusa.Entidades.Ent_tticol125[] recuperarCliente(whusa.Entidades.Ent_tticol125 parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfazServicioWhusa/listaRegistrosOrden_Param", ReplyAction="http://tempuri.org/InterfazServicioWhusa/listaRegistrosOrden_ParamResponse")]
        System.Data.DataTable listaRegistrosOrden_Param(ref whusa.Entidades.Ent_tticol125 parametros);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviaDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enviaDatos", Namespace="http://tempuri.org/", Order=0)]
        public whusap.ServiceReference1.enviaDatosRequestBody Body;
        
        public enviaDatosRequest() {
        }
        
        public enviaDatosRequest(whusap.ServiceReference1.enviaDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class enviaDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public whusap.ServiceReference1.Ent_tticol125[] parametros;
        
        public enviaDatosRequestBody() {
        }
        
        public enviaDatosRequestBody(whusap.ServiceReference1.Ent_tticol125[] parametros) {
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviaDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enviaDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public whusap.ServiceReference1.enviaDatosResponseBody Body;
        
        public enviaDatosResponse() {
        }
        
        public enviaDatosResponse(whusap.ServiceReference1.enviaDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class enviaDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public whusap.ServiceReference1.Ent_tticol125[] enviaDatosResult;
        
        public enviaDatosResponseBody() {
        }
        
        public enviaDatosResponseBody(whusap.ServiceReference1.Ent_tticol125[] enviaDatosResult) {
            this.enviaDatosResult = enviaDatosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InterfazServicioWhusaChannel : whusap.ServiceReference1.InterfazServicioWhusa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfazServicioWhusaClient : System.ServiceModel.ClientBase<whusap.ServiceReference1.InterfazServicioWhusa>, whusap.ServiceReference1.InterfazServicioWhusa {
        
        public InterfazServicioWhusaClient() {
        }
        
        public InterfazServicioWhusaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterfazServicioWhusaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfazServicioWhusaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfazServicioWhusaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        whusap.ServiceReference1.enviaDatosResponse whusap.ServiceReference1.InterfazServicioWhusa.enviaDatos(whusap.ServiceReference1.enviaDatosRequest request) {
            return base.Channel.enviaDatos(request);
        }
        
        public whusap.ServiceReference1.Ent_tticol125[] enviaDatos(whusap.ServiceReference1.Ent_tticol125[] parametros) {
            whusap.ServiceReference1.enviaDatosRequest inValue = new whusap.ServiceReference1.enviaDatosRequest();
            inValue.Body = new whusap.ServiceReference1.enviaDatosRequestBody();
            inValue.Body.parametros = parametros;
            whusap.ServiceReference1.enviaDatosResponse retVal = ((whusap.ServiceReference1.InterfazServicioWhusa)(this)).enviaDatos(inValue);
            return retVal.Body.enviaDatosResult;
        }
        
        public whusa.Entidades.Ent_tticol125[] CambiaEstado(whusa.Entidades.Ent_tticol125 parametros) {
            return base.Channel.CambiaEstado(parametros);
        }
        
        public whusa.Entidades.Ent_tticol125[] recuperarCliente(whusa.Entidades.Ent_tticol125 parametros) {
            return base.Channel.recuperarCliente(parametros);
        }
        
        public System.Data.DataTable listaRegistrosOrden_Param(ref whusa.Entidades.Ent_tticol125 parametros) {
            return base.Channel.listaRegistrosOrden_Param(ref parametros);
        }
    }
}
