//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace whusap.whusap.WCFService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ent_tticol125", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Ent_tticol125 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pdnoField;
        
        private int ponoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string itemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cwarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string clotField;
        
        private int reqtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateField;
        
        private int prinField;
        
        private int confField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string refcntdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string refcntuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idrecordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string pdno {
            get {
                return this.pdnoField;
            }
            set {
                if ((object.ReferenceEquals(this.pdnoField, value) != true)) {
                    this.pdnoField = value;
                    this.RaisePropertyChanged("pdno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int pono {
            get {
                return this.ponoField;
            }
            set {
                if ((this.ponoField.Equals(value) != true)) {
                    this.ponoField = value;
                    this.RaisePropertyChanged("pono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string item {
            get {
                return this.itemField;
            }
            set {
                if ((object.ReferenceEquals(this.itemField, value) != true)) {
                    this.itemField = value;
                    this.RaisePropertyChanged("item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cwar {
            get {
                return this.cwarField;
            }
            set {
                if ((object.ReferenceEquals(this.cwarField, value) != true)) {
                    this.cwarField = value;
                    this.RaisePropertyChanged("cwar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string clot {
            get {
                return this.clotField;
            }
            set {
                if ((object.ReferenceEquals(this.clotField, value) != true)) {
                    this.clotField = value;
                    this.RaisePropertyChanged("clot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int reqt {
            get {
                return this.reqtField;
            }
            set {
                if ((this.reqtField.Equals(value) != true)) {
                    this.reqtField = value;
                    this.RaisePropertyChanged("reqt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                if ((object.ReferenceEquals(this.dateField, value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int prin {
            get {
                return this.prinField;
            }
            set {
                if ((this.prinField.Equals(value) != true)) {
                    this.prinField = value;
                    this.RaisePropertyChanged("prin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int conf {
            get {
                return this.confField;
            }
            set {
                if ((this.confField.Equals(value) != true)) {
                    this.confField = value;
                    this.RaisePropertyChanged("conf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string refcntd {
            get {
                return this.refcntdField;
            }
            set {
                if ((object.ReferenceEquals(this.refcntdField, value) != true)) {
                    this.refcntdField = value;
                    this.RaisePropertyChanged("refcntd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string refcntu {
            get {
                return this.refcntuField;
            }
            set {
                if ((object.ReferenceEquals(this.refcntuField, value) != true)) {
                    this.refcntuField = value;
                    this.RaisePropertyChanged("refcntu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string mess {
            get {
                return this.messField;
            }
            set {
                if ((object.ReferenceEquals(this.messField, value) != true)) {
                    this.messField = value;
                    this.RaisePropertyChanged("mess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string idrecord {
            get {
                return this.idrecordField;
            }
            set {
                if ((object.ReferenceEquals(this.idrecordField, value) != true)) {
                    this.idrecordField = value;
                    this.RaisePropertyChanged("idrecord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="whusap.WCFService.InterfazServicioWhusa")]
    public interface InterfazServicioWhusa {
        
        // CODEGEN: Generating message contract since element name parametros from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfazServicioWhusa/enviaDatos", ReplyAction="http://tempuri.org/InterfazServicioWhusa/enviaDatosResponse")]
        whusap.whusap.WCFService.enviaDatosResponse enviaDatos(whusap.whusap.WCFService.enviaDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/InterfazServicioWhusa/enviaDatos", ReplyAction="http://tempuri.org/InterfazServicioWhusa/enviaDatosResponse")]
        System.IAsyncResult BeginenviaDatos(whusap.whusap.WCFService.enviaDatosRequest request, System.AsyncCallback callback, object asyncState);
        
        whusap.whusap.WCFService.enviaDatosResponse EndenviaDatos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfazServicioWhusa/CambiaEstado", ReplyAction="http://tempuri.org/InterfazServicioWhusa/CambiaEstadoResponse")]
        whusa.Entidades.Ent_tticol125[] CambiaEstado(whusa.Entidades.Ent_tticol125 parametros);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/InterfazServicioWhusa/CambiaEstado", ReplyAction="http://tempuri.org/InterfazServicioWhusa/CambiaEstadoResponse")]
        System.IAsyncResult BeginCambiaEstado(whusa.Entidades.Ent_tticol125 parametros, System.AsyncCallback callback, object asyncState);
        
        whusa.Entidades.Ent_tticol125[] EndCambiaEstado(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfazServicioWhusa/recuperarCliente", ReplyAction="http://tempuri.org/InterfazServicioWhusa/recuperarClienteResponse")]
        whusa.Entidades.Ent_tticol125[] recuperarCliente(whusa.Entidades.Ent_tticol125 parametros);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/InterfazServicioWhusa/recuperarCliente", ReplyAction="http://tempuri.org/InterfazServicioWhusa/recuperarClienteResponse")]
        System.IAsyncResult BeginrecuperarCliente(whusa.Entidades.Ent_tticol125 parametros, System.AsyncCallback callback, object asyncState);
        
        whusa.Entidades.Ent_tticol125[] EndrecuperarCliente(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfazServicioWhusa/listaRegistrosOrden_Param", ReplyAction="http://tempuri.org/InterfazServicioWhusa/listaRegistrosOrden_ParamResponse")]
        System.Data.DataTable listaRegistrosOrden_Param(ref whusa.Entidades.Ent_tticol125 parametros);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/InterfazServicioWhusa/listaRegistrosOrden_Param", ReplyAction="http://tempuri.org/InterfazServicioWhusa/listaRegistrosOrden_ParamResponse")]
        System.IAsyncResult BeginlistaRegistrosOrden_Param(ref whusa.Entidades.Ent_tticol125 parametros, System.AsyncCallback callback, object asyncState);
        
        System.Data.DataTable EndlistaRegistrosOrden_Param(ref whusa.Entidades.Ent_tticol125 parametros, System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviaDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enviaDatos", Namespace="http://tempuri.org/", Order=0)]
        public whusap.whusap.WCFService.enviaDatosRequestBody Body;
        
        public enviaDatosRequest() {
        }
        
        public enviaDatosRequest(whusap.whusap.WCFService.enviaDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class enviaDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public whusap.whusap.WCFService.Ent_tticol125[] parametros;
        
        public enviaDatosRequestBody() {
        }
        
        public enviaDatosRequestBody(whusap.whusap.WCFService.Ent_tticol125[] parametros) {
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviaDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enviaDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public whusap.whusap.WCFService.enviaDatosResponseBody Body;
        
        public enviaDatosResponse() {
        }
        
        public enviaDatosResponse(whusap.whusap.WCFService.enviaDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class enviaDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public whusap.whusap.WCFService.Ent_tticol125[] enviaDatosResult;
        
        public enviaDatosResponseBody() {
        }
        
        public enviaDatosResponseBody(whusap.whusap.WCFService.Ent_tticol125[] enviaDatosResult) {
            this.enviaDatosResult = enviaDatosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InterfazServicioWhusaChannel : whusap.whusap.WCFService.InterfazServicioWhusa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class enviaDatosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public enviaDatosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public whusap.whusap.WCFService.Ent_tticol125[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((whusap.whusap.WCFService.Ent_tticol125[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CambiaEstadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CambiaEstadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public whusa.Entidades.Ent_tticol125[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((whusa.Entidades.Ent_tticol125[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class recuperarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public recuperarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public whusa.Entidades.Ent_tticol125[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((whusa.Entidades.Ent_tticol125[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class listaRegistrosOrden_ParamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public listaRegistrosOrden_ParamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public whusa.Entidades.Ent_tticol125 parametros {
            get {
                base.RaiseExceptionIfNecessary();
                return ((whusa.Entidades.Ent_tticol125)(this.results[0]));
            }
        }
        
        public System.Data.DataTable Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfazServicioWhusaClient : System.ServiceModel.ClientBase<whusap.whusap.WCFService.InterfazServicioWhusa>, whusap.whusap.WCFService.InterfazServicioWhusa {
        
        private BeginOperationDelegate onBeginenviaDatosDelegate;
        
        private EndOperationDelegate onEndenviaDatosDelegate;
        
        private System.Threading.SendOrPostCallback onenviaDatosCompletedDelegate;
        
        private BeginOperationDelegate onBeginCambiaEstadoDelegate;
        
        private EndOperationDelegate onEndCambiaEstadoDelegate;
        
        private System.Threading.SendOrPostCallback onCambiaEstadoCompletedDelegate;
        
        private BeginOperationDelegate onBeginrecuperarClienteDelegate;
        
        private EndOperationDelegate onEndrecuperarClienteDelegate;
        
        private System.Threading.SendOrPostCallback onrecuperarClienteCompletedDelegate;
        
        private BeginOperationDelegate onBeginlistaRegistrosOrden_ParamDelegate;
        
        private EndOperationDelegate onEndlistaRegistrosOrden_ParamDelegate;
        
        private System.Threading.SendOrPostCallback onlistaRegistrosOrden_ParamCompletedDelegate;
        
        public InterfazServicioWhusaClient() {
        }
        
        public InterfazServicioWhusaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterfazServicioWhusaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfazServicioWhusaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfazServicioWhusaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<enviaDatosCompletedEventArgs> enviaDatosCompleted;
        
        public event System.EventHandler<CambiaEstadoCompletedEventArgs> CambiaEstadoCompleted;
        
        public event System.EventHandler<recuperarClienteCompletedEventArgs> recuperarClienteCompleted;
        
        public event System.EventHandler<listaRegistrosOrden_ParamCompletedEventArgs> listaRegistrosOrden_ParamCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        whusap.whusap.WCFService.enviaDatosResponse whusap.whusap.WCFService.InterfazServicioWhusa.enviaDatos(whusap.whusap.WCFService.enviaDatosRequest request) {
            return base.Channel.enviaDatos(request);
        }
        
        public whusap.whusap.WCFService.Ent_tticol125[] enviaDatos(whusap.whusap.WCFService.Ent_tticol125[] parametros) {
            whusap.whusap.WCFService.enviaDatosRequest inValue = new whusap.whusap.WCFService.enviaDatosRequest();
            inValue.Body = new whusap.whusap.WCFService.enviaDatosRequestBody();
            inValue.Body.parametros = parametros;
            whusap.whusap.WCFService.enviaDatosResponse retVal = ((whusap.whusap.WCFService.InterfazServicioWhusa)(this)).enviaDatos(inValue);
            return retVal.Body.enviaDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult whusap.whusap.WCFService.InterfazServicioWhusa.BeginenviaDatos(whusap.whusap.WCFService.enviaDatosRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginenviaDatos(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginenviaDatos(whusap.whusap.WCFService.Ent_tticol125[] parametros, System.AsyncCallback callback, object asyncState) {
            whusap.whusap.WCFService.enviaDatosRequest inValue = new whusap.whusap.WCFService.enviaDatosRequest();
            inValue.Body = new whusap.whusap.WCFService.enviaDatosRequestBody();
            inValue.Body.parametros = parametros;
            return ((whusap.whusap.WCFService.InterfazServicioWhusa)(this)).BeginenviaDatos(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        whusap.whusap.WCFService.enviaDatosResponse whusap.whusap.WCFService.InterfazServicioWhusa.EndenviaDatos(System.IAsyncResult result) {
            return base.Channel.EndenviaDatos(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public whusap.whusap.WCFService.Ent_tticol125[] EndenviaDatos(System.IAsyncResult result) {
            whusap.whusap.WCFService.enviaDatosResponse retVal = ((whusap.whusap.WCFService.InterfazServicioWhusa)(this)).EndenviaDatos(result);
            return retVal.Body.enviaDatosResult;
        }
        
        private System.IAsyncResult OnBeginenviaDatos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            whusap.whusap.WCFService.Ent_tticol125[] parametros = ((whusap.whusap.WCFService.Ent_tticol125[])(inValues[0]));
            return this.BeginenviaDatos(parametros, callback, asyncState);
        }
        
        private object[] OnEndenviaDatos(System.IAsyncResult result) {
            whusap.whusap.WCFService.Ent_tticol125[] retVal = this.EndenviaDatos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnenviaDatosCompleted(object state) {
            if ((this.enviaDatosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.enviaDatosCompleted(this, new enviaDatosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void enviaDatosAsync(whusap.whusap.WCFService.Ent_tticol125[] parametros) {
            this.enviaDatosAsync(parametros, null);
        }
        
        public void enviaDatosAsync(whusap.whusap.WCFService.Ent_tticol125[] parametros, object userState) {
            if ((this.onBeginenviaDatosDelegate == null)) {
                this.onBeginenviaDatosDelegate = new BeginOperationDelegate(this.OnBeginenviaDatos);
            }
            if ((this.onEndenviaDatosDelegate == null)) {
                this.onEndenviaDatosDelegate = new EndOperationDelegate(this.OnEndenviaDatos);
            }
            if ((this.onenviaDatosCompletedDelegate == null)) {
                this.onenviaDatosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnenviaDatosCompleted);
            }
            base.InvokeAsync(this.onBeginenviaDatosDelegate, new object[] {
                        parametros}, this.onEndenviaDatosDelegate, this.onenviaDatosCompletedDelegate, userState);
        }
        
        public whusa.Entidades.Ent_tticol125[] CambiaEstado(whusa.Entidades.Ent_tticol125 parametros) {
            return base.Channel.CambiaEstado(parametros);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCambiaEstado(whusa.Entidades.Ent_tticol125 parametros, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCambiaEstado(parametros, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public whusa.Entidades.Ent_tticol125[] EndCambiaEstado(System.IAsyncResult result) {
            return base.Channel.EndCambiaEstado(result);
        }
        
        private System.IAsyncResult OnBeginCambiaEstado(object[] inValues, System.AsyncCallback callback, object asyncState) {
            whusa.Entidades.Ent_tticol125 parametros = ((whusa.Entidades.Ent_tticol125)(inValues[0]));
            return this.BeginCambiaEstado(parametros, callback, asyncState);
        }
        
        private object[] OnEndCambiaEstado(System.IAsyncResult result) {
            whusa.Entidades.Ent_tticol125[] retVal = this.EndCambiaEstado(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCambiaEstadoCompleted(object state) {
            if ((this.CambiaEstadoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CambiaEstadoCompleted(this, new CambiaEstadoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CambiaEstadoAsync(whusa.Entidades.Ent_tticol125 parametros) {
            this.CambiaEstadoAsync(parametros, null);
        }
        
        public void CambiaEstadoAsync(whusa.Entidades.Ent_tticol125 parametros, object userState) {
            if ((this.onBeginCambiaEstadoDelegate == null)) {
                this.onBeginCambiaEstadoDelegate = new BeginOperationDelegate(this.OnBeginCambiaEstado);
            }
            if ((this.onEndCambiaEstadoDelegate == null)) {
                this.onEndCambiaEstadoDelegate = new EndOperationDelegate(this.OnEndCambiaEstado);
            }
            if ((this.onCambiaEstadoCompletedDelegate == null)) {
                this.onCambiaEstadoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCambiaEstadoCompleted);
            }
            base.InvokeAsync(this.onBeginCambiaEstadoDelegate, new object[] {
                        parametros}, this.onEndCambiaEstadoDelegate, this.onCambiaEstadoCompletedDelegate, userState);
        }
        
        public whusa.Entidades.Ent_tticol125[] recuperarCliente(whusa.Entidades.Ent_tticol125 parametros) {
            return base.Channel.recuperarCliente(parametros);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginrecuperarCliente(whusa.Entidades.Ent_tticol125 parametros, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginrecuperarCliente(parametros, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public whusa.Entidades.Ent_tticol125[] EndrecuperarCliente(System.IAsyncResult result) {
            return base.Channel.EndrecuperarCliente(result);
        }
        
        private System.IAsyncResult OnBeginrecuperarCliente(object[] inValues, System.AsyncCallback callback, object asyncState) {
            whusa.Entidades.Ent_tticol125 parametros = ((whusa.Entidades.Ent_tticol125)(inValues[0]));
            return this.BeginrecuperarCliente(parametros, callback, asyncState);
        }
        
        private object[] OnEndrecuperarCliente(System.IAsyncResult result) {
            whusa.Entidades.Ent_tticol125[] retVal = this.EndrecuperarCliente(result);
            return new object[] {
                    retVal};
        }
        
        private void OnrecuperarClienteCompleted(object state) {
            if ((this.recuperarClienteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.recuperarClienteCompleted(this, new recuperarClienteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void recuperarClienteAsync(whusa.Entidades.Ent_tticol125 parametros) {
            this.recuperarClienteAsync(parametros, null);
        }
        
        public void recuperarClienteAsync(whusa.Entidades.Ent_tticol125 parametros, object userState) {
            if ((this.onBeginrecuperarClienteDelegate == null)) {
                this.onBeginrecuperarClienteDelegate = new BeginOperationDelegate(this.OnBeginrecuperarCliente);
            }
            if ((this.onEndrecuperarClienteDelegate == null)) {
                this.onEndrecuperarClienteDelegate = new EndOperationDelegate(this.OnEndrecuperarCliente);
            }
            if ((this.onrecuperarClienteCompletedDelegate == null)) {
                this.onrecuperarClienteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnrecuperarClienteCompleted);
            }
            base.InvokeAsync(this.onBeginrecuperarClienteDelegate, new object[] {
                        parametros}, this.onEndrecuperarClienteDelegate, this.onrecuperarClienteCompletedDelegate, userState);
        }
        
        public System.Data.DataTable listaRegistrosOrden_Param(ref whusa.Entidades.Ent_tticol125 parametros) {
            return base.Channel.listaRegistrosOrden_Param(ref parametros);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginlistaRegistrosOrden_Param(ref whusa.Entidades.Ent_tticol125 parametros, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginlistaRegistrosOrden_Param(ref parametros, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Data.DataTable EndlistaRegistrosOrden_Param(ref whusa.Entidades.Ent_tticol125 parametros, System.IAsyncResult result) {
            return base.Channel.EndlistaRegistrosOrden_Param(ref parametros, result);
        }
        
        private System.IAsyncResult OnBeginlistaRegistrosOrden_Param(object[] inValues, System.AsyncCallback callback, object asyncState) {
            whusa.Entidades.Ent_tticol125 parametros = ((whusa.Entidades.Ent_tticol125)(inValues[0]));
            return this.BeginlistaRegistrosOrden_Param(ref parametros, callback, asyncState);
        }
        
        private object[] OnEndlistaRegistrosOrden_Param(System.IAsyncResult result) {
            whusa.Entidades.Ent_tticol125 parametros = this.GetDefaultValueForInitialization<whusa.Entidades.Ent_tticol125>();
            System.Data.DataTable retVal = this.EndlistaRegistrosOrden_Param(ref parametros, result);
            return new object[] {
                    parametros,
                    retVal};
        }
        
        private void OnlistaRegistrosOrden_ParamCompleted(object state) {
            if ((this.listaRegistrosOrden_ParamCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.listaRegistrosOrden_ParamCompleted(this, new listaRegistrosOrden_ParamCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void listaRegistrosOrden_ParamAsync(whusa.Entidades.Ent_tticol125 parametros) {
            this.listaRegistrosOrden_ParamAsync(parametros, null);
        }
        
        public void listaRegistrosOrden_ParamAsync(whusa.Entidades.Ent_tticol125 parametros, object userState) {
            if ((this.onBeginlistaRegistrosOrden_ParamDelegate == null)) {
                this.onBeginlistaRegistrosOrden_ParamDelegate = new BeginOperationDelegate(this.OnBeginlistaRegistrosOrden_Param);
            }
            if ((this.onEndlistaRegistrosOrden_ParamDelegate == null)) {
                this.onEndlistaRegistrosOrden_ParamDelegate = new EndOperationDelegate(this.OnEndlistaRegistrosOrden_Param);
            }
            if ((this.onlistaRegistrosOrden_ParamCompletedDelegate == null)) {
                this.onlistaRegistrosOrden_ParamCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnlistaRegistrosOrden_ParamCompleted);
            }
            base.InvokeAsync(this.onBeginlistaRegistrosOrden_ParamDelegate, new object[] {
                        parametros}, this.onEndlistaRegistrosOrden_ParamDelegate, this.onlistaRegistrosOrden_ParamCompletedDelegate, userState);
        }
    }
}
